exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/pages-themes/primer"
  
title: Yaowen Zheng
description: Yaowen Zheng's website

analytics:
  provider: "google"
  google:
    tracking_id: "UA-78697215-1"
    anonymize_ip: false # default
